version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: [ "version update" ]
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    reviewers:
      - atick-faisal
      
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    registries: "*"
    labels: [ "version update" ]
    groups:
      all-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    reviewers:
      - atick-faisal
      
registries:
  maven-google:
    type: "maven-repository"
    url: "https://maven.google.com"
    replaces-base: true
