name: Docs

on:
  push:
    branches:
      - main

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        # https://github.com/mkdocs/mkdocs/issues/2370
        with:
          fetch-depth: 0

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v5

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Test README quality
        uses: atick-faisal/llm-readme-tester@v1.1.2
        with:
          google_api_key: ${{ secrets.GOOGLE_API_KEY }}
          checks: "all"

      - name: Generate Docs
        run: |
          pip install mkdocs mkdocs-material Pygments
          ./gradlew dokkaGfmMultiModule --no-configuration-cache
          mv build/dokka/gfmMultiModule docs
          cat README.md > docs/index.md
          mkdocs gh-deploy

# https://github.com/softprops/action-gh-release/issues/236
permissions:
  contents: write
